name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Node unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node: ['12', '14', '16']
        node: ['16']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.6
          run_install: true

      - name: Container Mongo cache
        id: mongo-cache
        uses: actions/cache@v2
        env:
          image_tag: mongo:5.0.7
        with:
          path: ~/mongo-cache
          key: mongo-cache-${{ runner.os }}-${{env.image_tag}}

      - if: steps.mongo-cache.outputs.cache-hit != 'true'
        run: |
          docker pull $image_tag
          docker save -o ~/mongo-cache/mongo.tar $image_tag

      - if: steps.mongo-cache.outputs.cache-hit == 'true'
        run: docker load -i ~/mongo-cache/mongo.tar

      - name: Run tests
        run: |
          pnpm test:ci
        env:
          CI: true
